name: Develop
on: 
  push:
    branches:
      - develop
    
jobs:
  build-firebase-staging:
    name: Build staging firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: functions
      - working-directory: functions
        # run: yarn install --frozen-lockfile
        run: npm t
      - working-directory: functions
        run: yarn build
      - name: Archive firebase functions
        uses: actions/upload-artifact@master
        with:
          name: firebase-functions-staging
          path: functions/lib
  
  firebase-staging:
    name: Deploy firebase to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: firebase-functions-staging
          path: functions/lib
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: quotes-staging-d5139

  # integration:
