name: Develop
on: 
  push:
    branches:
      - develop-OFFLINE
    
jobs:
  # build:
  
  firebase-functinos:
    name: Deploy firebase functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - working-directory: functions
        run: yarn install --frozen-lockfile
      - working-directory: functions
        run: yarn build
      - name: Deploy functions to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: quotes-553ed

  # integration:
