name: Develop
on: 
  push:
    branches:
      - develop
    
jobs:
  # build-firebase-staging:
  #   #TODO: only execute when file changes in functions/**/*
  #   name: Build staging firebase
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     # yarn install with caching
  #     - uses: bahmutov/npm-install@v1
  #       with:
  #         working-directory: functions
  #     - working-directory: functions
  #       run: yarn build
  #     - name: Archive firebase functions
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: firebase-functions-staging
  #         path: functions/lib
  
  # firebase-staging:
  #   #TODO: only execute when file changes in functions/**/*
  #   name: Deploy firebase to staging
  #   runs-on: ubuntu-latest
  #   needs: build-firebase-staging
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: firebase-functions-staging
  #         path: functions/lib
  #     # yarn install with caching
  #     - uses: bahmutov/npm-install@v1
  #       with:
  #         working-directory: functions
  #     - name: Deploy to firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only functions,firestore:rules
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #         PROJECT_ID: quotes-staging-d5139

  ## Disabled to use 1 job for debug speed
  # build-staging:
  #   name: Build staging
  #   # needs: firebase-staging
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v1
  #     - uses: bahmutov/npm-install@v1 
  #     - run: yarn build:staging
  #     - name: Archive dist:staging
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: dist-staging
  #         path: dist

  ui-tests:
    name: UI Tests
    # needs: build-staging
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        # machines: [1, 2, 3]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      # Install is run separately from test so that dependencies are available
      # for other steps
      # - name: Install Dependencies
      #   uses: cypress-io/github-action@v1
      #   with:
      #     # just perform install
      #     runTests: false
      #     build: yarn build:staging
      # - uses: bahmutov/npm-install@v1 
      # - run: yarn build:staging
      ## Use 1 job for debug speed
      # - name: Download Artifact
      #   uses: actions/download-artifact@master
      #   with:
      #     name: dist-staging
      #     path: dist

      # Cypress action manages installing/caching npm dependencies and Cypress binary.
      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          install: true
          start: yarn start:staging
          build: yarn build:staging
          group: 'E2E Tests'
          record: true
          parallel: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_TEST_UID: ${{ secrets.STAGING_TEST_UID }}
          SERVICE_ACCOUNT: ${{ secrets.STAGING_SERVICE_ACCOUNT }}
          FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
