name: Firebase deploy
on:
  push:
    paths:
      - 'functions/src/**.ts'
    branches:
      - master 

jobs:
  build-and-deploy:
    name: Deploy functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - working-directory: functions
        run: yarn install --frozen-lockfile
      - working-directory: functions
        run: yarn build
      - name: Deploy functions to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: quotes-553ed
