name: Netlify deploy

on: 
  push:
    branches:
      - master
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn ng build --prod
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist/quotes --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

#     steps:
#     - name: Deploy to Netlify
#       uses: netlify/actions/cli@master
#       with:
#         args: deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=public
#       env:
#         CD: true

# workflow "Publish on Netlify" {
#   on = "push"
#   resolves = ["Publish"]
# }

# action "Publish" {
#   uses = "netlify/actions/build@master"
#   secrets = ["GITHUB_TOKEN", "NETLIFY_SITE_ID"]
# }
