name: Pull request
on: 
  pull_request
    
jobs:
  build-quotes:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: functions
      - working-directory: functions
        run: yarn build
      - working-directory: functions
        run: yarn test
      - name: Archive firebase functions
        uses: actions/upload-artifact@master
        with:
          name: quotes-functions
          path: functions/lib
      - uses: bahmutov/npm-install@v1
      - run: yarn ngcc
      - run: yarn build:prod
      - name: Archive quotes
        uses: actions/upload-artifact@master
        with:
          name: quotes
          path: dist/quotes/

  deploy-on-staging:
    name: Deploy quotes to staging
    runs-on: ubuntu-latest
    needs: build-quotes
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: quotes-functions
          path: functions/lib
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: functions
      - uses: bahmutov/npm-install@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: quotes
          path: dist/quotes
      - run: yarn publish-env
        env:
          FIREBASE_API_KEY: ${{ secrets.STAGING_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.STAGING_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.STAGING_FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.STAGING_FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.STAGING_FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.STAGING_FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.STAGING_FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.STAGING_FIREBASE_MEASUREMENT_ID }}
          ANGULAR_PRODUCTION: ${{ secrets.STAGING_ANGULAR_PRODUCTION }}
      - run: yarn firebase use ${{ secrets.STAGING_FIREBASE_PROJECT_ID }}
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - run: yarn deploy
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  ui-tests:
    name: UI Tests
    needs: deploy-on-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: quotes
          path: dist/quotes
      - run: yarn publish-env
        env:
          FIREBASE_API_KEY: ${{ secrets.STAGING_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.STAGING_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.STAGING_FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.STAGING_FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.STAGING_FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.STAGING_FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.STAGING_FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.STAGING_FIREBASE_MEASUREMENT_ID }}
          ANGULAR_PRODUCTION: ${{ secrets.STAGING_ANGULAR_PRODUCTION }}
      - run: yarn serve
      - run: yarn test:ci
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_TEST_UID: ${{ secrets.STAGING_TEST_UID }}
          FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          SERVICE_ACCOUNT: ${{ secrets.STAGING_SERVICE_ACCOUNT }}
